"""Shared constants and helpers for the web-search step: trusted Vietnamese news sites and diacritics stripping."""

import re

VIET_NEWS_SITES = [
    # Major outlets
    "vov.vn",
    "cand.com.vn",
    "kiemsat.vn",
    "thoibaotaichinhvietnam.vn",
    "tapchitaichinh.vn",
    "thoibaonganhang.vn",
    "tapchinganhang.gov.vn",
    "tapchitoaan.vn",
    "tapchibaohiemxahoi.gov.vn",
    "vietnam.vnanet.vn",
    "thanhtra.com.vn",
    "thanhtravietnam.vn",
    "qdnd.vn",
    "nongnghiep.vn",
    "baovanhoa.vn",
    "vanhoanghethuat.vn",
    "giaoducthoidai.vn",
    "daibieunhandan.vn",
    "vietq.vn",
    "qltt.vn",
    "vtcnews.vn",
    "haiquanonline.com.vn",
    "consosukien.vn",
    "congthuong.vn",
    "toquoc.vn",
    "baophapluat.vn",
    "baodautu.vn",
    "baodauthau.vn",
    "baovephapluat.vn",
    "thuenhanuoc.vn",
    "thethaovanhoa.vn",
    "kinhtevadubao.vn",
    "baogiaothong.vn",
    "tapchigiaothong.vn",
    "ictvietnam.vn",
    "baodantoc.vn",
    "baohaiquanvietnam.vn",
    "dantocmiennui.vn",
    "vietnamplus.vn",
    "tapchicongthuong.vn",
    "baoquocte.vn",
    "vietnamnet.vn",
    "baochinhphu.vn",
    "dantri.com.vn",
    "vnexpress.net",
    "suckhoedoisong.vn",
    "congly.vn",
    "baoxaydung.com.vn",
    "tapchixaydung.vn",
    "tapchigiaoduc.edu.vn",
    "tcnn.vn",
    "tapchikhoahocnongnghiep.vn",
    "baokiemtoan.vn",
    "antoanthongtin.vn",
    "vjst.vn",
    "baotainguyenmoitruong.vn",
    "tainguyenvamoitruong.vn",
    "vtv.vn",
    "daidoanket.vn",
    "laodong.vn",
    "nhandan.vn",
    "dangcongsan.vn",
    "thanhnien.vn",
    "phunuvietnam.vn",
    "kienthuc.net.vn",
    "trithuccuocsong.vn",
    "tienphong.vn",
    "bongdaplus.vn",
    "laodongcongdoan.vn",
    "phunumoi.net.vn",
    "nguoiduatin.vn",
    "diendandoanhnghiep.vn",
    "congnghevadoisong.vn",
    "1thegioi.vn",
    "markettimes.vn",
    "tapchithangmay.vn",
    "taichinhdoanhnghiep.net.vn",
    "vneconomy.vn",
    "arttimes.vn",
    "congluan.vn",
    "thoidai.com.vn",
    "kinhtechungkhoan.vn",
    "nhandaoonline.vn",
    "chatluongvacuocsong.vn",
    "giaoduc.net.vn",
    "mekongasean.vn",
    "znews.vn",
    "thuonghieucongluan.com.vn",
    "tapchinongthonmoi.vn",
    "baovannghe.com.vn",
    "thegioidisan.vn",
    "ngaymoionline.com.vn",
    "petrotimes.vn",
    "thuonggiaonline.vn",
    "kinhdoanhvabienmau.vn",
    "dientungaynay.vn",
    "dientuungdung.vn",
    "doithoaiphattrien.vn",
    "lyluanchinhtrivatruyenthong.vn",
    "thanhnienviet.vn",
    "nghenhinvietnam.vn",
    "vnmedia.vn",
    "vanhienplus.vn",
    "vanhoavaphattrien.vn",
    "phaply.net.vn",
    "phapluatphattrien.vn",
    "nld.com.vn",
    # Local TV stations
    "atv.org.vn",
    "brt.vn",
    "bacgiangtv.vn",
    "backantv.vn",
    "thbl.vn",
    "bacninhtv.vn",
    "thbt.vn",
    "binhdinhtv.vn",
    "btv.org.vn",
    "bptv.org.vn",
    "binhthuantv.vn",
    "ctvcamau.vn",
    "canthotv.vn",
    "caobangtv.vn",
    "danangtv.vn",
    "daklak.gov.vn",
    "daknong.gov.vn",
    "dienbientv.vn",
    "dnrtv.org.vn",
    "thdt.vn",
    "gialaitv.vn",
    "hagiangtv.vn",
    "hanamtv.vn",
    "hanoionline.vn",
    "hatinhtv.vn",
    "haiduongtv.com.vn",
    "thhp.vn",
    "haugiangtivi.vn",
    "hoabinhtv.vn",
    "hungyentv.vn",
    "ktv.org.vn",
    "kgtv.vn",
    "kontumtv.vn",
    "laichautv.vn",
    "lamdongtv.vn",
    "langsontv.vn",
    "laocaitv.vn",
    "la34.com.vn",
    "namdinhtv.vn",
    "truyenhinhnghean.vn",
    "nbtv.vn",
    "ninhthuantv.vn",
    "phuthotv.vn",
    "ptpphuyen.vn",
    "qbtv.vn",
    "qrt.vn",
    "quangngaitv.vn",
    "qtv.vn",
    "quangtritv.vn",
    "thst.vn",
    "sonlatv.vn",
    "tayninh.gov.vn",
    "thaibinhtv.vn",
    "thainguyentv.vn",
    "truyenhinhthanhhoa.vn",
    "trthue.vn",
    "thtg.vn",
    "htv.com.vn",
    "travinhtv.vn",
    "tuyenquangtv.vn",
    "thvl.vn",
    "vinhphuctv.vn",
    "yenbaitv.org.vn",
]


def remove_diacritics(text: str) -> str:
    """Strip Vietnamese diacritics from `text` and lowercase it."""
    s = text.lower()
    s = re.sub(r"[àáạảãâầấậẩẫăằắặẳẵ]", "a", s)
    s = re.sub(r"[èéẹẻẽêềếệểễ]", "e", s)
    s = re.sub(r"[ìíịỉĩ]", "i", s)
    s = re.sub(r"[òóọỏõôồốộổỗơờớợởỡ]", "o", s)
    s = re.sub(r"[ùúụủũưừứựửữ]", "u", s)
    s = re.sub(r"[ỳýỵỷỹ]", "y", s)
    s = re.sub(r"[đ]", "d", s)
    return s
